# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5fbe0b466e4c32f8e80ee47e9cc90148e4cc50aee02967057e6e6e91c4b27f867ba61ed8012a78d2a4029aa153a683f8c0d18349bfd22ecc11d22fe52b53b82

test:
  secret_key_base: 28a133098111906022e87513a8ed9c111d4a2222ece63a0b17e90bbb68ab0bb54fd311f27cfa8cb0adba935a103721c70c8575f74dbe3703c291a4050d22531f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
